name = "영지전"
author = "94hyuns"
version = "1.0.34"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e4642c788f3ddefb0058c96a6bded28409d3dc0a0a8d89e139e9d6616584dd8"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
