name = "영지전"
author = "94hyuns"
version = "1.0.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3dba1b233c0918ec801b2b5499245299603ac120768ff4cf68e91a3b32fe66c1"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
